### ISSUE TITLE
Adding VMs to Backend Pools

### ISSUE THREAD

**Issue by horsey** [Azure/terraform-azurerm-loadbalancer#11]
Currently, the ```terraform-azurerm-loadbalancer``` module does not add VMs to the Backend Pool configuration. I understand that some information from the compute module is required for this to happen. 

Can the information required from the compute module be made optional parameters to make this happen?
This is very useful when one wants to create VMs and attach them to the loadbalancer without manual intervention.

**Comment by horsey** [comment]
@dtzar Any thoughts on this one?

**Comment by dtzar** [comment]
This makes sense - someone just needs to spend the time to make it happen.  IMO it should be an update to the dependent compute module(s) which utilize it to be able to add them to the pool.

**Comment by horsey** [comment]
I agree that this should be done on the compute module instead. However, the loadbalancer module has to be triggered only when a variable, for example, ```lb = "true"``` is set. Is there a way to achieve this in Terraform?

**Comment by dcaro** [comment]
@horsey I have added this in our backlog.

**Comment by twittyc** [comment]
Is there an update on this? It is blocking some of our terraform deployments. Thanks.

**Comment by theharleyquin** [comment]
Still not seeing this in official documentation or support - don't know if @mitchellmaler's process is still accurate or supported

**Comment by ernani** [comment]
Hi, I've tried here and it complains of adding the load_balancer_backend_address_pool_ids to the ip_configurations of the network interface

**Comment by VigneshVGITHub** [comment]
Does this work fully?

**Comment by yupwei68** [comment]
Hi @horsey  , thanks for opening this issue. As @ernani said, you could create a `azurerm_network_interface_backend_address_pool_association` to associate the exported `backend_address_pool_id` with `network_interface_id` of your VM. Please refer to document https://www.terraform.io/docs/providers/azurerm/r/network_interface_backend_address_pool_association.html for more details. 
Sorry that I have to close this issue, and sorry for the delay. Please reopen it if anything unclear.

**Comment by vpernankil** [comment]
> Hi @horsey , thanks for opening this issue. As @ernani said, you could create a `azurerm_network_interface_backend_address_pool_association` to associate the exported `backend_address_pool_id` with `network_interface_id` of your VM. Please refer to document https://www.terraform.io/docs/providers/azurerm/r/network_interface_backend_address_pool_association.html for more details.
> Sorry that I have to close this issue, and sorry for the delay. Please reopen it if anything unclear.

Thanks for the reply . It worked !!! :)
