### ISSUE TITLE
2 count parameters in "azurerm_lb_nat_rule" "azlb" resource

### ISSUE THREAD

**Issue by horsey** [Azure/terraform-azurerm-loadbalancer#12]
I observe that there are 2 count parameters in the ```azurerm_lb_nat_rule``` resource: 
 ``` count                          = "${length(var.remote_port)}" ```  
& 
```  count                          = "${var.number_of_endpoints}"```
Is this intentional? If so, how does it play out during execution?

**Comment by horsey** [comment]
I see that PR #10 fixes this. Not merged it?

**Comment by dtzar** [comment]
Correct 10 PR fixes this.  I'm waiting on someone else to review my code so it can get merged.

**Comment by dcaro** [comment]
@horsey, thanks for opening this issue. I have just approved and merged #10.
