### ISSUE TITLE
How to attach two Azure NIC's with a standard load balancer???

### ISSUE THREAD

**Issue by Ashjoker24** [Azure/terraform-azurerm-loadbalancer#20]
I want to connect my load balancer with two NIC's in azure using terraform.how can i do that??

**Comment by sdcscripts** [comment]
Hi, 

You can use this to associate NICs to backendpools on your load balancer. https://www.terraform.io/docs/providers/azurerm/r/network_interface_backend_address_pool_association.html

Regards
Shaun

**Comment by sdcscripts** [comment]
Hi, you should be able to use this to associate, 
https://www.terraform.io/docs/providers/azurerm/r/network_interface_backend_address_pool_association.html

Regards
Shaun

**Comment by yupwei68** [comment]
Hi @Ashjoker24 , thanks for opening this issue. Since @sdcscripts has replied your issue, I'd like to close it if no further questions have been pushed.
