### ISSUE TITLE
Multiple depreciation warnings when using latest TF version v12.16

### ISSUE THREAD

**Issue by josem0287** [Azure/terraform-azurerm-loadbalancer#22]
The following warning is repeated multiple times when deploying the module:

Warning: Interpolation-only expressions are deprecated

There are so many warnings in the output that the terraform plan is almost unreadable.

Please upgrade the syntax of the main.tf and variables.tf files in the module to use the latest syntax (0.12)

**Comment by yupwei68** [comment]
hi @josem0287, we'are about to release v2.0.0 to support terraform v0.12

**Comment by MihaiAnei** [comment]
This is a blocker for us to use the official Azure TF modules. Any updates on this? Anything I can help with?

**Comment by yupwei68** [comment]
Hi @josem0287  , thanks for opening this issue. Sorry that I have to close this issue for v2.0.0 has been released.
