### ISSUE TITLE
Error Creating multiple lb rules

### ISSUE THREAD

**Issue by satheeshpanampilly** [Azure/terraform-azurerm-loadbalancer#24]
Hello,

I tried to use your loadbalancer module code to my project. There are multiple errors i face when used. Details below.

1.  Not able to multiple ports allow.
Error:-
When try to use as below, outputs error.
  "lb_port" {
    http  = ["80", "Tcp", "80"]
    https = ["443", "Tcp", "443"]
  }

Error message:-
  "lb_ports"   {
Argument names must not be quoted.

And when i tried as below, it worked.
lb_port = {
    http  = ["80", "Tcp", "80"]
    https = ["443", "Tcp", "443"]
  }

2. Now after allowing first port "http  = ["80", "Tcp", "80"]" , then it says azurerm_lbrule already exists. Not allowing second port rule to create ie "https = ["443", "Tcp", "443"]"

Please revert.
Thanx,
Satheesh

**Comment by yupwei68** [comment]
Hi @satheeshpanampilly , thanks for opening this issue. I have corrected our README example to be applied successfully. Please try our latest release.
