### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by schmichri** [Azure/terraform-azurerm-loadbalancer#25]
@dtzar  Are you still sheparding this project? It's not working in the latest TF Version.

**Comment by dtzar** [comment]
No sorry, an engineering team took over quite awhile ago and they removed me from having access to merge.

**Comment by schmichri** [comment]
```
Latest commit
ffb9ef9
on Aug 16, 2018
```

Well I would say they didn't do a good job ;-)

**Comment by dtzar** [comment]
I feel ya 😔

**Comment by yupwei68** [comment]
Hi @schmichri , thanks for opening this issue. Sorry for the delay. Currently v2.0.0 who supports Terraform v0.12 has been released. Sorry that I have to close this issue.
