### ISSUE TITLE
enable_floating_ip value be passed as a variable instead of hard coding the value to false.

### ISSUE THREAD

**Issue by enuguris** [Azure/terraform-azurerm-loadbalancer#39]
Hi,

Can you please enable_floating_ip  value be passed as a variable instead of hard coding the value to false.

**Comment by Lddeiva** [comment]
Hi @enuguris ,

Please use this attribute and pass the value as the parameter.

![image](https://user-images.githubusercontent.com/61077834/146520281-701c716a-5e81-4e32-96e2-29b4a81ac095.png)


https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_rule

Please feel free to close the issue if this works.
