### ISSUE TITLE
Provider 3.1.0 - Issue with azurerm_lb_probe

### ISSUE THREAD

**Issue by wellingk** [Azure/terraform-azurerm-loadbalancer#44]
Hiya,

Recently Upgraded to TF Provider 3.1.0 for Azure.  This is causing an issue with my Local Balancer Probes.

Here is an example of my code for the LB Probe: -

resource "azurerm_lb_probe" "external_https" {
  resource_group_name = azurerm_resource_group.my-rg.name
  loadbalancer_id     = azurerm_lb.my-lb
  name                = "external_https"
  port                = 443
}

When I run a Terraform Plan my output is: -

Error: Unsupported argument

  on my-load-balancers.tf line 70, in resource "azurerm_lb_probe" "external_https":
  70:   resource_group_name = azurerm_resource_group.my-rg.name

An argument named "resource_group_name" is not expected here.

So, I remove the line resource_group_name = azurerm_resource_group.my-rg.name

and then I get a message that  says I do need the Resource group name within the IDE

**Comment by jiaweitao001** [comment]
Hi @wellingk , according to the official doc, `resource_group_name` is no longer supported in `azurerm_lb_probe`, you don't have to use an IDE to run your TF code. If you have further questions regarding `azurerm_lb_probe` resource, it's highly recommended to open the issue in the dedicated Azurerm repo [here](https://github.com/hashicorp/terraform-provider-azurerm/issues). Thanks!
