### ISSUE TITLE
Missing "sku_tier" from resource type "azurerm_lb"

### ISSUE THREAD

**Issue by ashishjullia** [Azure/terraform-azurerm-loadbalancer#45]
As per the official documentation of resource type "azurerm_lb" -> [Link](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb#:~:text=sku_tier%20%2D%20(-,Optional,-)%20sku_tier%20%2D%20(Optional)%20The)

The resource does support an attribute (although it is optional) "sku_tier" but the module "loadbalancer"
 doesn't support the same.
 
 It would be a + if a patch for the same is included in the next commit.

**Comment by rishabhgargg** [comment]
The loadbalancer resource in Azure supports the flag "sku_tier" which helps in deploying ths loadbalancer as 'regional' or 'global' .
As the resource "azurerm_lb" supports this flag, it will be helpful in using this official module for the same.
