### ISSUE TITLE
output "azurerm_public_ip_address"

### ISSUE THREAD

**Issue by asote** [Azure/terraform-azurerm-loadbalancer#9]
Error when using output "azurerm_public_ip_address"

output "lb_Public_IP" {
  value = "${module.loadbalancer.azurerm_public_ip_address}"
}

Error: output 'lb_Public_IP': "azurerm_public_ip_address" is not a valid output for module "loadbalancer"

Using Terraform v0.11.1

**Comment by dtzar** [comment]
This is the same problem as here.  https://github.com/Azure/terraform-azurerm-compute/issues/34 
Going to close this issue and track there.
